target_gp_name: "Italian Grand Prix"
data_dir: "Data"
model_data_dir: "Scripts/ModelData"
results_dir: "Scripts/Results"
cleaned_data_filename_template: "{safe_gp_name}_cleaned_data.csv"
xgb_params_subdir: "xgboost/sw/params"
xgb_params_filename_template: "{safe_gp_name}_xgb_params_sw.json"
xgb_models_subdir: "xgboost/sw/models"
xgb_model_filename_template: "{safe_gp_name}_xgb_model_sw.json"
xgb_model_metadata_filename_template: "{safe_gp_name}_xgb_model_sw_metadata.json"
lr_models_subdir: "linear_regression/sw/models"
lr_model_filename_template: "{safe_gp_name}_lr_model_sw.pkl"
lr_model_metadata_filename_template: "{safe_gp_name}_lr_model_sw_metadata.json"
target_col: "LapTime_seconds"
lap_col: "LapNumber"
numerical_features: [TyreLife, LapNumber, Humidity_RBF_Median, Pressure_RBF_Median, TrackTemp_RBF_Median, WindSpeed_RBF_Median, TempDelta_RBF_Median, Year, LapTime_prev]
categorical_features: [Driver, Team, pirelliCompound]
holdout_ratio: 0.20
window_ratio: 0.20
window_train_ratio: 0.80
window_step_ratio: 0.20
alpha_cos: 0.50
beta_cos: 0.50
random_seed: 42
optuna_trials: 200
use_saved_xgb_params: true
xgb_optuna_sampler: "tpe"
xgb_learning_rate_min: 0.010
xgb_learning_rate_max: 0.020
xgb_max_depth_min: 5
xgb_max_depth_max: 6
xgb_min_child_weight_min: 6
xgb_min_child_weight_max: 12
xgb_subsample_min: 0.60
xgb_subsample_max: 0.72
xgb_colsample_bytree_min: 0.82
xgb_colsample_bytree_max: 0.92
xgb_gamma_min: 0.20
xgb_gamma_max: 0.80
xgb_reg_alpha_min: 0.0001
xgb_reg_alpha_max: 0.01
xgb_reg_lambda_min: 1.5
xgb_reg_lambda_max: 4.5
mlflow_enabled: true
mlflow_tracking_uri: "Scripts/Results/mlruns"
mlflow_experiment_name: "f1-lap-time-{safe_gp_name}"
